package com.waenhancer.xposed.features.devtools;

import android.app.Activity;
import android.content.SharedPreferences;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import com.waenhancer.xposed.core.Feature;
import com.waenhancer.xposed.core.WppCore;

/**
 * Lifecycle manager for the Element Inspector overlay.
 *
 * <p>Observes the {@code inspector_session} preference via a {@link WppCore#addListenerActivity
 * activity state listener}. When the preference is armed with a non-empty session token, attaches
 * the {@link InspectorOverlay} to resumed activities and detaches it when activities are paused,
 * stopped, or when the session expires due to inactivity.
 *
 * <p>The overlay manages its own session state via touch-based renewal ({@link
 * InspectorSession#touched(long)}). This feature seeds the overlay's session once on first
 * RESUMED, then checks the overlay's live session for expiry on subsequent lifecycle events —
 * allowing true idle-timeout tracking even if the Activity stays RESUMED without further
 * lifecycle transitions.
 *
 * <p><b>Hard invariant (§6 of the spec):</b> with the pref empty at startup, {@code doHook()}
 * returns before registering any listener. This ensures no permanent hook exists when the feature
 * is off.
 */
public class InspectorFeature extends Feature {

    private InspectorOverlay currentOverlay;

    public InspectorFeature(
            @NonNull ClassLoader classLoader,
            @NonNull SharedPreferences preferences) {
        super(classLoader, preferences);
    }

    @Override
    @NonNull
    public String getPluginName() {
        return "Element Inspector";
    }

    @Override
    public void doHook() throws Throwable {
        // If the pref is empty or unset at startup, no listener is registered.
        // This satisfies the hard invariant: no permanent hook exists when the feature is off.
        if (parseSession(getSafeString("inspector_session", "")) == null) {
            return;
        }

        // Register a listener that will run for the life of the process.
        // It re-reads the pref on each activity state change to pick up live updates.
        WppCore.addListenerActivity((activity, type) -> {
            // Check if overlay's own session (which has been renewed via selections) has expired.
            if (currentOverlay != null) {
                InspectorSession overlaySession = currentOverlay.getSession();
                if (!overlaySession.isActive(System.currentTimeMillis())) {
                    // Session expired due to idle timeout (no selections for 10 minutes)
                    detach();
                    return;
                }
            }

            // Check if the pref is still armed (module may have disarmed it).
            String prefValue = getSafeString("inspector_session", "");
            InspectorSession parsed = parseSession(prefValue);

            if (parsed == null) {
                // Pref is empty, disarm
                detach();
                return;
            }

            // Pref is armed; handle activity lifecycle.
            switch (type) {
                case RESUMED:
                    if (currentOverlay == null) {
                        // First attach to this activity — create overlay and seed its session
                        attachTo(activity, parsed);
                    }
                    // If overlay already exists, don't recreate it; let it keep managing
                    // its own session state via touch-based renewal.
                    break;
                case PAUSED:
                case ENDED:
                    detach();
                    break;
            }
        });
    }

    /**
     * Parses the {@code inspector_session} preference value.
     *
     * <p><b>Format:</b> {@code token|timestamp} (pipe-delimited), where:
     * <ul>
     *   <li>{@code token} is the unique session identifier (generated by Task B4)</li>
     *   <li>{@code timestamp} is when the session was armed (informational, for detecting
     *       re-arm events if needed)</li>
     * </ul>
     *
     * <p>Returns {@code null} if the value is empty, null, or malformed. On a well-formed value,
     * reconstructs a fresh session from the current time with a 10-minute idle timeout via
     * {@link InspectorSession#armed(String, long)}.
     */
    @Nullable
    private InspectorSession parseSession(@Nullable String value) {
        if (value == null || value.isEmpty()) {
            return null;
        }

        try {
            String[] parts = value.split("\\|");
            if (parts.length != 2) {
                return null;
            }
            String token = parts[0];
            // The timestamp field (parts[1]) is parsed but not used for expiry computation.
            // Instead, the overlay's own session (seeded here, renewed via touches) drives
            // idle-timeout detection. The timestamp can be used in future enhancements
            // (e.g., detecting module re-arm events).
            return InspectorSession.armed(token, System.currentTimeMillis());
        } catch (Exception e) {
            return null;
        }
    }

    /**
     * Attaches the overlay to the given activity and seeds its session.
     *
     * <p>Called only on first RESUMED after the pref becomes armed. The overlay's session is
     * seeded with the armed session; subsequent renewals come from the overlay's own touch
     * handler ({@link InspectorOverlay#onContentTouch}).
     */
    private void attachTo(@NonNull Activity activity, @NonNull InspectorSession session) {
        // Should not happen, but guard against double-attach.
        if (currentOverlay != null) {
            return;
        }

        // Create a new overlay anchored to this activity.
        // The onExit runnable will be called if the user clicks the "Exit inspector" button.
        currentOverlay = new InspectorOverlay(activity, this::detach);
        currentOverlay.setSession(session);
        currentOverlay.attach();
    }

    /**
     * Detaches the overlay if it is currently attached.
     */
    private void detach() {
        if (currentOverlay != null) {
            currentOverlay.detach();
            currentOverlay = null;
        }
    }
}
